name: Security Scans

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: execute gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          
  grype:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: execute grype
        uses: anchore/scan-action@v4
        with:
          path: "."
          fail-build: false
